#ifndef _MDLATTACHMENTSECTION_H
#define _MDLATTACHMENTSECTION_H
#include <stdint.h>
#include "MDLGENOBJECT.h"
#include "MDLKEYTRACK.h"
#include "MDLALPHAKEYFRAME.h"

class MDLATTACHMENTSECTION {
public:
	MDLATTACHMENTSECTION();
	MDLATTACHMENTSECTION(const MDLATTACHMENTSECTION *a2);
	~MDLATTACHMENTSECTION();
};
#endif