#include "MDLATTACHMENTSECTION.h"

MDLATTACHMENTSECTION::MDLATTACHMENTSECTION()
{
}
MDLATTACHMENTSECTION::MDLATTACHMENTSECTION( const MDLATTACHMENTSECTION& that)
{
	mdx = that.mdx;
	mdl = that.mdl;
}
MDLATTACHMENTSECTION::~MDLATTACHMENTSECTION()
{
}

bool MDLATTACHMENTSECTION::parse(char*& binary,int& rest)
{
	return true;
}
