#include "MDLATTACHMENTSECTION.h"

MDLATTACHMENTSECTION::MDLATTACHMENTSECTION():
	OBJ(0x800u),
	KATV(2),
	AttachmentID(0)
{
	Path[0] = 0;
}
MDLATTACHMENTSECTION::MDLATTACHMENTSECTION( const MDLATTACHMENTSECTION& that):
	OBJ(that.OBJ),
	KATV(that.KATV),
	AttachmentID(that.AttachmentID)
{
	memcpy(Path, that.Path, 260);
}
MDLATTACHMENTSECTION::~MDLATTACHMENTSECTION()
{
}