#include "MDLBONESECTION.h"

MDLBONESECTION::MDLBONESECTION():
	OBJ(0x100u)
{
	GeosetID = 0;
	GeosetAnimID = 0;
}
MDLBONESECTION::MDLBONESECTION(const MDLBONESECTION& that):
	OBJ(that.OBJ)
{
	GeosetID = that.GeosetID;
	GeosetAnimID = that.GeosetAnimID;
}
MDLBONESECTION::~MDLBONESECTION()
{
}
