#include "MDLEVENTSECTION.h"

MDLEVENTSECTION::MDLEVENTSECTION():
	val1(0x400u)
{
}
MDLEVENTSECTION::MDLEVENTSECTION(const MDLEVENTSECTION& that): 
	val1(that.val1),
	val2(that.val2)
{
}
MDLEVENTSECTION::~MDLEVENTSECTION()
{
}