#include "MDLEVENTTRACK.h"

MDLEVENTTRACK::MDLEVENTTRACK()
{
	//MDLKEYTRACK<MDLEVENTKEY>::MDLKEYTRACK(this, 0);
}
MDLEVENTTRACK::MDLEVENTTRACK( const MDLEVENTTRACK *a2)
{
	//MDLKEYTRACK<MDLEVENTKEY>::MDLKEYTRACK(this, a2);
}
MDLEVENTTRACK::~MDLEVENTTRACK()
{
	//MDLKEYTRACK<MDLEVENTKEY>::~MDLKEYTRACK(this);
}