#include "MDLFLIPBOOKTRACK.h"

MDLFLIPBOOKTRACK::MDLFLIPBOOKTRACK()
{
	//MDLKEYTRACK<MDLFLIPBOOKKEY>::MDLKEYTRACK(this, 0);
}
MDLFLIPBOOKTRACK::MDLFLIPBOOKTRACK( const MDLFLIPBOOKTRACK *a2)
{
	//MDLKEYTRACK<MDLFLIPBOOKKEY>::MDLKEYTRACK(this, a2);
}
MDLFLIPBOOKTRACK::~MDLFLIPBOOKTRACK()
{
	//MDLKEYTRACK<MDLFLIPBOOKKEY>::~MDLKEYTRACK(this);
}