#ifndef _MDLFLOATPROPKEYFRAME_H
#define _MDLFLOATPROPKEYFRAME_H
#include <stdint.h>

class MDLFLOATPROPKEYFRAME {
public:
	MDLFLOATPROPKEYFRAME();
	MDLFLOATPROPKEYFRAME(const MDLFLOATPROPKEYFRAME& that);
public:
	long x, y, z, w;
};
#endif