#include "MDLFLIPBOOKTRACK.h"

MDLFLIPBOOKTRACK::MDLFLIPBOOKTRACK():val(0)
{
}
MDLFLIPBOOKTRACK::MDLFLIPBOOKTRACK(const MDLFLIPBOOKTRACK& that):val(that.val)
{
}
MDLFLIPBOOKTRACK::~MDLFLIPBOOKTRACK()
{
}