#include "MDLGLOBALSEQSECTION.h"

MDLGLOBALSEQSECTION::MDLGLOBALSEQSECTION()
{
	durations = 0;
}

MDLGLOBALSEQSECTION::MDLGLOBALSEQSECTION(const MDLGLOBALSEQSECTION& that)
{
	durations = that.durations;
}
