#include "MDLINTTRACK.h"

MDLINTTRACK::MDLINTTRACK()
{
 // MDLKEYTRACK<MDLINTKEY>::MDLKEYTRACK(this, 0);
}
MDLINTTRACK::MDLINTTRACK( const MDLINTTRACK *a2)
{
  //MDLKEYTRACK<MDLINTKEY>::MDLKEYTRACK(this, a2);
}
MDLINTTRACK::~MDLINTTRACK()
{
  //MDLKEYTRACK<MDLINTKEY>::~MDLKEYTRACK(this);
}