#ifndef _MDLINTENSITYKEYFRAME_H
#define _MDLINTENSITYKEYFRAME_H
#include <stdint.h>

class MDLINTENSITYKEYFRAME {
public:
	MDLINTENSITYKEYFRAME();
	MDLINTENSITYKEYFRAME(const MDLINTENSITYKEYFRAME& that);
public:
	long x, y, z, w;
};
#endif