#include "MDLLIGHTSECTION.h"

MDLLIGHTSECTION::MDLLIGHTSECTION()
{
	//MDLGENOBJECT::MDLGENOBJECT(this, 0x200u);
	Type = 0;
	//MDLKEYTRACK<MDLATTENKEYFRAME>::MDLKEYTRACK((char *)this + 168, 2);
	AttStart = 0;
	//MDLKEYTRACK<MDLATTENKEYFRAME>::MDLKEYTRACK((char *)this + 196, 2);
	AttEnd = 0;
	//MDLKEYTRACK<MDLCOLORKEYFRAME>::MDLKEYTRACK((char *)this + 224, 2);
	ColR = 1065353216;
	ColG = 1065353216;
	ColB = 1065353216;
	//MDLKEYTRACK<MDLINTENSITYKEYFRAME>::MDLKEYTRACK((char *)this + 260, 2);
	Intensity = 0;
	//MDLKEYTRACK<MDLCOLORKEYFRAME>::MDLKEYTRACK((char *)this + 288, 2);
	AmbColR = 1065353216;
	AmbColG = 1065353216;
	AmbColB = 1065353216;
	//MDLKEYTRACK<MDLINTENSITYKEYFRAME>::MDLKEYTRACK((char *)this + 324, 2);
	AmbIntensity = 0;
	//MDLKEYTRACK<MDLALPHAKEYFRAME>::MDLKEYTRACK((char *)this + 352, 2);
}
MDLLIGHTSECTION::MDLLIGHTSECTION( const MDLLIGHTSECTION& that)
{
	//MDLGENOBJECT::MDLGENOBJECT(this, a2);
	Type = that.Type;
	//MDLKEYTRACK<MDLATTENKEYFRAME>::MDLKEYTRACK((char *)this + 168, (char *)a2 + 168);
	AttStart = that.AttStart;
	//MDLKEYTRACK<MDLATTENKEYFRAME>::MDLKEYTRACK((char *)this + 196, (char *)a2 + 196);
	AttEnd = that.AttEnd;
	//MDLKEYTRACK<MDLCOLORKEYFRAME>::MDLKEYTRACK((char *)this + 224, (char *)a2 + 224);
	ColR = that.ColR;
	ColG = that.ColG;
	ColB = that.ColB;
	//MDLKEYTRACK<MDLINTENSITYKEYFRAME>::MDLKEYTRACK((char *)this + 260, (char *)a2 + 260);
	Intensity = that.Intensity;
	//MDLKEYTRACK<MDLCOLORKEYFRAME>::MDLKEYTRACK((char *)this + 288, (char *)a2 + 288);
	AmbColR = that.AmbColR;
	AmbColG = that.AmbColG;
	AmbColB = that.AmbColB;
	//MDLKEYTRACK<MDLINTENSITYKEYFRAME>::MDLKEYTRACK((char *)this + 324, (char *)a2 + 324);
	AmbIntensity = that.AmbIntensity;
	//MDLKEYTRACK<MDLALPHAKEYFRAME>::MDLKEYTRACK((char *)this + 352, (char *)a2 + 352);
}
MDLLIGHTSECTION::~MDLLIGHTSECTION()
{
}