#ifndef _MDLPARTICLEEMITTER2_H
#define _MDLPARTICLEEMITTER2_H
#include <stdint.h>
#include "MDLGENOBJECT.h"
#include "MDLALPHAKEYFRAME.h"
#include "MDLFLOATPROPKEYFRAME.h"

class MDLPARTICLEEMITTER2 {
public:
	MDLPARTICLEEMITTER2();
	MDLPARTICLEEMITTER2(const MDLPARTICLEEMITTER2 *a2);
	~MDLPARTICLEEMITTER2();
};
#endif