#include "MDLPARTICLEEMITTER2.h"

MDLPARTICLEEMITTER2::MDLPARTICLEEMITTER2()
{
}
MDLPARTICLEEMITTER2::MDLPARTICLEEMITTER2( const MDLPARTICLEEMITTER2& that)
{
}
MDLPARTICLEEMITTER2::~MDLPARTICLEEMITTER2()
{
}
bool MDLPARTICLEEMITTER2::parse(char*& binary,int& rest)
{
	return true;
}

