#ifndef _MDLRIBBONEMITTER_H
#define _MDLRIBBONEMITTER_H
#include <stdint.h>
#include "MDLINTTRACK.h"
#include "MDLGENOBJECT.h"
#include "MDLCOLORKEYFRAME.h"
#include "MDLALPHAKEYFRAME.h"
#include "MDLFLOATPROPKEYFRAME.h"

class MDLRIBBONEMITTER {
public:
	MDLRIBBONEMITTER();
	MDLRIBBONEMITTER(const MDLRIBBONEMITTER *a2);
	~MDLRIBBONEMITTER();
};
#endif