#include "MDLSOUNDEMITTERSECTION.h"

MDLSOUNDEMITTERSECTION::MDLSOUNDEMITTERSECTION()
{
	//MDLGENOBJECT::MDLGENOBJECT(this, 0);
	//MDLSOUNDTRACK::MDLSOUNDTRACK((MDLSOUNDEMITTERSECTION *)((char *)this + 164));
}
MDLSOUNDEMITTERSECTION::MDLSOUNDEMITTERSECTION( const MDLSOUNDEMITTERSECTION *a2)
{
	//MDLGENOBJECT::MDLGENOBJECT(this, a2);
	//return MDLSOUNDTRACK::MDLSOUNDTRACK(
	//	(MDLSOUNDEMITTERSECTION *)((char *)this + 164),
	//	(const MDLSOUNDEMITTERSECTION *)((char *)a2 + 164));
}
MDLSOUNDEMITTERSECTION::~MDLSOUNDEMITTERSECTION()
{
	//MDLSOUNDTRACK::~MDLSOUNDTRACK((MDLSOUNDEMITTERSECTION *)((char *)this + 164));
	//MDLGENOBJECT::~MDLGENOBJECT(this);
}