#ifndef _MDLSOUNDEMITTERSECTION_H
#define _MDLSOUNDEMITTERSECTION_H
#include <stdint.h>
#include "MDLGENOBJECT.h"
#include "MDLSOUNDTRACK.h"

class MDLSOUNDEMITTERSECTION {
public:
	MDLSOUNDEMITTERSECTION();
	MDLSOUNDEMITTERSECTION(const MDLSOUNDEMITTERSECTION& that);
	~MDLSOUNDEMITTERSECTION();
public:
	MDLGENOBJECT OBJ;
	MDLSOUNDTRACK SOUNDS;
};
#endif