#include "MDLSOUNDTRACK.h"

MDLSOUNDTRACK::MDLSOUNDTRACK()
{
	//MDLKEYTRACK<MDLSOUNDKEYFRAME>::MDLKEYTRACK(this, 4);
}
MDLSOUNDTRACK::MDLSOUNDTRACK( const MDLSOUNDTRACK *a2)
{
	//MDLKEYTRACK<MDLSOUNDKEYFRAME>::MDLKEYTRACK(this, a2);
}
MDLSOUNDTRACK::~MDLSOUNDTRACK()
{
	//MDLKEYTRACK<MDLSOUNDKEYFRAME>::~MDLKEYTRACK(this);
}