#include "MDLTEXANIMSECTION.h"

MDLTEXANIMSECTION::MDLTEXANIMSECTION():
	KTAT(2),
	KTAR(2),
	KTAS(2)
{
}
MDLTEXANIMSECTION::MDLTEXANIMSECTION(const MDLTEXANIMSECTION& that):
	KTAT(that.KTAT),
	KTAR(that.KTAR),
	KTAS(that.KTAS)
{
}
MDLTEXANIMSECTION::~MDLTEXANIMSECTION()
{
}