#include "MDLTARGETSECTION.h"

MDLTARGETSECTION::MDLTARGETSECTION():
	KCTR(2)
{
	x = 0;
	y = 0;
	z = 0;
}
MDLTARGETSECTION::MDLTARGETSECTION( const MDLTARGETSECTION& that):
	KCTR(that.KCTR)
{
	x = that.x;
	y = that.y;
	z = that.z;
}
MDLTARGETSECTION::~MDLTARGETSECTION()
{
}