#ifndef _MDLTEXANIMSECTION_H
#define _MDLTEXANIMSECTION_H
#include <stdint.h>
#include "MDLKEYTRACK.h"
#include "MDLTRANSKEYFRAME.h"
#include "MDLROTKEYFRAME.h"
#include "MDLSCALEKEYFRAME.h"

class MDLTEXANIMSECTION {
public:
	MDLTEXANIMSECTION();
	MDLTEXANIMSECTION(const MDLTEXANIMSECTION *a2);
	~MDLTEXANIMSECTION();
};
#endif